{
 "title": "NATS v22",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "NS",
    "label": "namespace",
    "query": {
     "query": "label_values(nats_duration_count{}, service_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(nats_duration_count{service_namespace=\"$NS\"}, service)"
    }
   },
   {
    "name": "quantile",
    "query": "\"0.5\",\"0.9\",\"0.99\""
   },
   { "name": "Filters" },
   {
    "name": "stage",
    "query": {
     "query": "label_values(nats_duration_count{service_namespace=\"$NS\"}, deployment_environment)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "label_values(nats_count{service_namespace=\"$NS\"}, kind_of)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Services versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(runtime_uptime{service_namespace=\"$NS\"}[1m])) by ( namespace, service, service_version)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "repeat": "license",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(runtime_uptime{service_namespace=\"$NS\",deployment_environment=\"$stage\"}[30s])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{service_namespace=\"$NS\", service=~\"$service\",deployment_environment=\"$stage\"}[ $__interval])) by(state,service_instance_id,service)",
     "legendFormat": "{{ service }} | {{state}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(process_runtime_go_goroutines{service_namespace=\"$NS\", deployment_environment=\"$stage\", service_name=~\"$service\"}) by (service_instance_id, service)",
     "legendFormat": "{{service}} | {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_go_gc_pause_total_ns{service_namespace=\"$NS\", service_name=~\"$service\",deployment_environment=\"$stage\"}[$__interval])) by (service_instance_id, service)",
     "legendFormat": "{{service}} | {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_sys{service_namespace=\"$NS\", service_name=~\"$service\",deployment_environment=\"$stage\"}) by (service_instance_id)",
     "legendFormat": "virtual address space {{service_instance_id}}"
    },
    {
     "expr": "sum(process_runtime_go_mem_heap_alloc{service_namespace=\"$NS\", service_name=~\"$service\",deployment_environment=\"$stage\"}) by (service, service_instance_id)",
     "legendFormat": "allocated heap object  {{service_instance_id}} "
    },
    {
     "expr": "sum(process_runtime_go_mem_heap_inuse{service_namespace=\"$NS\", service_name=~\"$service\",deployment_environment=\"$stage\"}) by (service, service_instance_id)",
     "legendFormat": "in-use spans {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_alloc{service_name=~\"$service\", service_namespace=\"$NS\"}",
     "legendFormat": "bytes allocated | {{service_instance_id}}"
    },
    {
     "expr": "process_runtime_go_mem_heap_inuse{service_name=~\"$service\", service_namespace=\"$NS\"}",
     "legendFormat": "heap inuse | {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{service_namespace=\"$NS\", service_name=~\"$service\",deployment_environment=\"$stage\"} / 1024 / 1024",
     "legendFormat": "{{state}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "NATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "grpc_service",
   "targets": [
    {}
   ]
  },
  {
   "title": "Operations <$kind>",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(nats_duration_count{service=~\"$service\",kind_of=~\"$kind\"}[$__range])) by (subject)",
     "legendFormat": "COUNT | {{subject}}"
    },
    {
     "expr": "sum(increase(nats_duration_count{service=~\"$service\",kind_of=~\"$kind\", error=\"true\"}[$__range])) by (subject) or\n (sum(increase(nats_duration_count{service=~\"$service\",kind_of=~\"$kind\"}[$__range])) by (subject) * 0)",
     "legendFormat": "COUNT | {{subject}}"
    },
    {
     "expr": "sum(increase(nats_duration_sum{service=~\"$service\",kind_of=~\"$kind\"}[$__range])) by (subject)",
     "legendFormat": "SUM: {{subject}}"
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(increase(nats_duration_sum{service=~\"$service\", service_namespace=\"$NS\", kind_of=~\"$kind\"}[$__range])) by (subject)\n/ sum(increase(nats_duration_count{service=~\"$service\", service_namespace=\"$NS\",kind_of=~\"$kind\"}[$__range])) by (subject)) >= 0",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "stat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_duration_count{service=~\"$service\",service_namespace=\"$NS\", kind_of=~\"$kind\"}[$__range]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "stat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(nats_duration_count{error=\"false\",service=~\"$service\",kind_of=~\"$kind\"}[$__range]))\n/ sum(increase(nats_duration_count{service=~\"$service\", kind_of=~\"$kind\"}[$__range])) >= 0)\nor (sum(increase(nats_duration_count{service=~\"$service\",kind_of=~\"$kind\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Operation per sec. by Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(increase(nats_duration_sum{service=~\"$service\", service_namespace=\"$NS\",kind_of=~\"$kind\"}[$__range])) by (error)\n/ sum(increase(nats_duration_count{service=~\"$service\", service_namespace=\"$NS\",kind_of=~\"$kind\"}[$__range])) by (error)) >= 0",
     "legendFormat": "IsError: {{error}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nats_duration_count{service=~\"$service\", service_namespace=\"$NS\", kind_of=~\"$kind\"}[$__range])) by (subject)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Average handling time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(nats_duration_sum{service=~\"$service\", service_namespace=\"$NS\",kind_of=~\"$kind\"}[$__range])) by (subject)",
     "legendFormat": "{{nats_subject}}"
    }
   ]
  },
  {
   "title": "Subscription statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(nats_subscriptions_send_count{ service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(nats_subscriptions_pending_msgs{service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(rate(nats_subscriptions_dropped_count{service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "[[quantile]]-quantile latency of requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile,\nsum(rate(nats_duration_bucket{service=~\"$service\", service_namespace=\"$NS\",kind_of=~\"$kind\"}[1m])) by (subject,le)\n)",
     "legendFormat": "{{nats_subject}}"
    }
   ]
  },
  {
   "title": "Request error percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nats_duration_count{service=~\"$service\", service_namespace=\"$NS\", error=\"false\"}[$__range])) by (subject)\n/ \nsum(rate(nats_duration_count{service=~\"$service\", service_namespace=\"$NS\", kind_of=~\"$kind\"}[$__range])) by (subject)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate((nats_content_length{service=~\"$service\",kind_of=~\"$kind\"}[$__range]))) by(kind_of)",
     "legendFormat": "{{kind_of}}"
    },
    {
     "expr": "sum(irate((nats_content_length{service=~\"$service\"}[$__range]))) by(kind_of)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_duration_count{service=~\"$service\", service_namespace=\"$NS\", error=\"true\", kind_of=~\"$kind\"}[$__range])) by (subject)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Subscription", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } }
 ]
}